"""Add patent, company, infringement_analysis tables

Revision ID: c164a7d41f07
Revises: 1a31ce608336
Create Date: 2024-11-16 21:18:56.638456

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c164a7d41f07'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('products', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('patent',
    sa.Column('publication_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignee', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority_date', sa.DateTime(), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('grant_date', sa.DateTime(), nullable=True),
    sa.Column('jurisdictions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('application_events', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('landscapes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('publish_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citations_non_patent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provenance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('inventors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('claims', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_publication_number'), 'patent', ['publication_number'], unique=True)
    op.create_table('infringementanalysis',
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('overall_risk_assessment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_infringing_products', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['company.name'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.publication_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infringementanalysis')
    op.drop_index(op.f('ix_patent_publication_number'), table_name='patent')
    op.drop_table('patent')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
